use_frameworks!

target 'SSuggestText' do
  pod "SSuggestText", :path => "../"

  	target 'Tests' do
  		inherit! :search_paths
  		pod "SSuggestText", :path => "../"

  		pod 'Specta'#,  :git => "https://github.com/specta/specta.git" #, '~> 0.3.0.beta1'
  		pod 'Expecta'
  		#pod 'FBSnapshotTestCase'
  		pod 'Expecta+Snapshots'
	end

end


