target 'SSuggestText', :exclusive => true do
  pod "SSuggestText", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SSuggestText", :path => "../"

  pod 'Specta'#,  :git => "https://github.com/specta/specta.git" #, '~> 0.3.0.beta1'
  pod 'Expecta'
  #pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
